# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2efd11f373643b3d0a7d4081626a630fafe9cacb390017b9b24aedb61722d852c523989a45fa103a6098e957fcc51f63ecc8ab1124d5dac64e11731ebc20a11d

test:
  secret_key_base: ee6b8695bdb2781e3a8bf85c95ca17318703a002ff56466b985886f547941fbd9a11109b4fcfd28042fe1107a68f4571ee32e6a599e17802ff3e6dfd7ed6c232

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
